### ISSUE TITLE
zmk, behaviour hold-tap

### ISSUE THREAD

**Issue by red-four** [nickcoutsos/keymap-editor#110]
Attempting to use a custom behaviour for hold-tap; not able to save. 

<img width="387" alt="behaviour" src="https://github.com/nickcoutsos/keymap-editor/assets/123419172/dd191f1f-ffc1-4031-9d9b-8a9224e4819a">
<img width="756" alt="Screenshot 2023-06-02 163515" src="https://github.com/nickcoutsos/keymap-editor/assets/123419172/91758b00-1ccd-452f-92a4-029ab4bf0860">

(If there is a better way to get this option, I am here for it).

**Comment by nickcoutsos** [comment]
Hi, thanks for the report! It looks like you're doing things correctly there as all of the required fields are filled in. I'm trying to reproduce this effect myself with the same parameters and it only happens if I haven't checked the _Enable Beta_ checkbox. Could you confirm if that's the case here?

**Comment by red-four** [comment]
I had the enable beta box clicked when I was making this.

**Comment by nickcoutsos** [comment]
Can you check the browser console for errors? If you're clicking Okay and nothing happens then that would suggest an error that isn't being caught.

**Comment by nickcoutsos** [comment]
Wait, I'm seeing in your other screenshot that the behavior exists because it's already bound to some keys. By save you mean commit? I'm seeing error logs for `red-four/reviung41-v3`, is that the repo in question? It looks like you've _removed_ it from your installation which means the app no longer has write permissions.

**Comment by red-four** [comment]
... ohhh. because I deleted and then remade it, but didn't give the new one permissions. That would do it.

**Comment by nickcoutsos** [comment]
Awesome, glad to hear that!
