### ISSUE TITLE
Delete layer button doesn't seem to work

### ISSUE THREAD

**Issue by ReFil** [nickcoutsos/keymap-editor#18]
When i click delete layer, it pops up the confirm message "really delete?" then I click ok and nothing happens, irrelevant of if the layer is on the keymap.json or a newly added one

**Comment by nickcoutsos** [comment]
Looking at the handler I'm wondering if that ever actually did anything because literally all it does is show the alert (which... if anything should have been `confirm()`). Thanks for the heads up, this wouldn't take too much to fix, just bubble something up to the keymap component and let it drop the layer (and name).

**Comment by ReFil** [comment]
This has been addressed by #20
