### ISSUE TITLE
Duplicate Layer

### ISSUE THREAD

**Issue by FabianoLothor** [nickcoutsos/keymap-editor#193]
I'd like to see this option available.

I probably could try and contribute to the project adding this feature if you want, it looks a simple and quick win.

**Comment by nickcoutsos** [comment]
That's a fair point, I've recently(-ish) added support for duplicating other node types so it wouldn't be terribly difficult to add here. I can take a look later this afternoon, most likely it would involve a new option in the layer actions dropdown.

**Comment by nickcoutsos** [comment]
Just pushed, have a look (refresh if you're still in the app) when you have a moment!

**Comment by FabianoLothor** [comment]
Working great, much appreciated!

**Comment by FabianoLothor** [comment]
Found a possible bug, hopefully you can reproduce by yourself:

1. Duplicate layer X.
2. Rename duplicated layer Y.
3. Save your changes.
  - I'm using github, unsure if happens with other sources.
4. Refresh the page or hit the refresh button.

Layer X is saved with the same name of layer Y.

That's likely happening due JS copying the reference of the previous object.

In the end, that's the result I'm getting:

![image](https://github.com/nickcoutsos/keymap-editor/assets/2192995/bbd57152-1768-4a24-901a-05ff2f26fc19)

It's annoying, but there is a workaround where we can just rename the layer X after the refresh.

**Comment by nickcoutsos** [comment]
Ah shit!

My mind went to the reference thing, too, but I'm actually deep-cloning the layer. That's the problem, incidentally, because when the keymap is parsed I store an index for each node to help manage changes (add/remove/reorder) to the collection. I should just need to remove the index property of the cloned node but I'll want to wait until morning and do some more testing. It would also mean that any changes you make to the duplicated layer's bindings would also blow out the original which would be incredibly annoying.

Thanks for catching this!

Edit: as a workaround (although still really annoying) you can probably duplicate a node, save, then fix the original node name and proceed to make other changes without further issues.

**Comment by nickcoutsos** [comment]
Should be resolved now! 🤞

**Comment by FabianoLothor** [comment]
Thank you, couldn't reproduce anymore, closing it.

**Comment by nickcoutsos** [comment]
Fantastic, thanks again @FabianoLothor!
