### ISSUE TITLE
Macro to hold Shift and press F1

### ISSUE THREAD

**Issue by Odaym** [nickcoutsos/keymap-editor#227]
Hi, I have some shortcuts for switching to different workspaces:
<img width="466" alt="Screenshot 2024-06-06 at 08 44 00" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/753054/2f20ece3-f810-4b5c-a76c-a2faafae0c12">

I wanted to make these as macros so that I could have the Hotkeys (1 and 2 for example) run them in 1 button.

I would like to know what I should be entering in these fields to achieve that, I'm really not sure what half of these fields mean and where to specify what I want to have, any help is appreciated, thanks a lot!

<img width="680" alt="Screenshot 2024-06-06 at 12 26 53" src="https://github.com/nickcoutsos/keymap-editor/assets/753054/23a7e3bc-cc4f-4f74-b971-ac8db679bb00">

**Comment by Odaym** [comment]
I think i need to stay in Macros and do this?

<img width="797" alt="Screenshot 2024-06-06 at 12 39 51" src="https://github.com/nickcoutsos/keymap-editor/assets/753054/cda9da88-b69e-4298-8d42-ad9f05839967">

**Comment by nickcoutsos** [comment]
That's the basic idea for the macro, but you'll also want to finish it off with `&macro_release` and another `&kp LSHFT` (or whichever shift you're using).

You may not necessarily need to do this as a macro, though. The more straightforward approach would be a bind like `&kp LS(F1)` which applies the modifier directly to the keycode. In the UI that would mean selecting the `F1` key code and applying the modifier like so:

<img width="856" alt="Screen Shot 2024-06-06 at 9 42 23 AM" src="https://github.com/nickcoutsos/keymap-editor/assets/1165066/1b3aceb4-8b0f-41e2-a0a0-865b92cf3149">

I know that there are some cases where the OS or specific software (usually games) don't like this because the modifier is pressed and released in the same HID report but if that isn't the case here you can avoid the extra work of setting up a macro.

**Comment by Odaym** [comment]
hi thanks for the response, ok but this means that now F1 will be automaticlly considered as Shift + F1, that still has me needing to press FN first, I want my Hotkeys in the Base layer (1, 2, 3, 4) to be pressed once and they can execute Shift + F1/2/3/4

Would that mean that after this step (modifier to F1 directly) then assign Hotkey 1 to F1 and that would be Shift + F1?

**Comment by nickcoutsos** [comment]
These can be done independently; you can have a layer where the F-keys are unmodified and another layer where they are. In that case the modifier would only affect the keycode it's attached to.

**Comment by Odaym** [comment]
lol I can just do the modifier + F1 on the Hotkey that I want, this literally should be all there is to it

<img width="966" alt="Screenshot 2024-06-06 at 17 01 19" src="https://github.com/nickcoutsos/keymap-editor/assets/753054/cac83b83-d200-4814-ac3e-cfdccda3bddd">

**Comment by Odaym** [comment]
yep, that was it! thanks a lot for your help!
